// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Usar PRISMA_DATABASE_URL con fallback a POSTGRES_URL (para Vercel)
    url: env("PRISMA_DATABASE_URL") || env("POSTGRES_URL"),
  },
});
